"""Project scaffolding for `tokensurf init` — Playwright-`init`-style starter project."""

from __future__ import annotations

from pathlib import Path

_EVAL_DETERMINISTIC = '''"""Starter eval: deterministic scorers.

Edit freely — this is your project now.

Run:
    tokensurf eval run evals/example_deterministic.py
"""

from __future__ import annotations

import tokensurf as ts

_ANSWERS = {
    "capital of France": "Paris",
    "capital of Japan": "Tokyo",
}


def task(question: str) -> str:
    with ts.span("lookup", type="tool", input=question) as sp:
        answer = _ANSWERS.get(question, "I don't know")
        sp.output = answer
        return answer


data = ts.Dataset.from_list(
    [
        {"id": "c1", "input": "capital of France", "expected": "Paris"},
        {"id": "c2", "input": "capital of Japan", "expected": "Tokyo"},
    ]
)

scorers: list[ts.Scorer] = [
    ts.ExactMatch(),
    ts.ToolSequence(expected=["lookup"]),
]
'''

_EVAL_LLM_JUDGE = '''"""Starter eval: an LLM judge, wired to an offline fake client so it runs
without a provider key. Swap FakeLLMClient for tokensurf.scorers.llm.LiteLLMClient
(or your own client implementing complete()) to grade with a real model.

Run:
    tokensurf eval run evals/example_llm_judge.py
"""

from __future__ import annotations

import tokensurf as ts
from tokensurf.scorers.llm import LLMResponse


class FakeLLMClient:
    def __init__(self, score: int = 8) -> None:
        self._score = score

    def complete(self, *, model: str, messages: list[dict[str, str]]) -> LLMResponse:
        return LLMResponse(text=str(self._score), model=model, cost=0.0, latency=0.0)


def task(question: str) -> str:
    with ts.span("answer", type="llm", input=question):
        return "Paris" if "France" in question else "I don't know"


data = ts.Dataset.from_list(
    [{"id": "c1", "input": "capital of France", "expected": "Paris"}]
)

scorers: list[ts.Scorer] = [
    ts.LLMJudge(criteria="answers the question correctly", client=FakeLLMClient(score=8)),
]
'''

_TEST_AGENT_QUALITY = '''"""Gate agent quality in CI: run `pytest evals/`.

Wires assert_eval to each starter eval so a regression fails the build, not just
prints a warning. Add one function per eval file as your project grows.
"""

from __future__ import annotations

import tokensurf as ts

from example_deterministic import data as det_data
from example_deterministic import scorers as det_scorers
from example_deterministic import task as det_task
from example_llm_judge import data as judge_data
from example_llm_judge import scorers as judge_scorers
from example_llm_judge import task as judge_task


def test_deterministic_quality() -> None:
    report = ts.evaluate(task=det_task, data=det_data, scorers=det_scorers)
    ts.assert_eval(report, min_pass_rate=1.0)


def test_llm_judge_quality() -> None:
    report = ts.evaluate(task=judge_task, data=judge_data, scorers=judge_scorers)
    ts.assert_eval(report, min_pass_rate=0.5)
'''

_README = """# Your TokenSurf test suite

Generated by `tokensurf init`.

## Run the example evals

```bash
tokensurf eval run evals/example_deterministic.py
tokensurf eval run evals/example_llm_judge.py
```

Each prints a console table and writes `results.jsonl`.

## Gate CI with pytest

```bash
cd evals && pytest .
```

## Write your own eval

Copy `evals/example_deterministic.py`, replace `task`/`data`/`scorers` with your own agent and
cases. See the full scorer catalog and SDK reference at
https://github.com/Cem-Bas/TokenSurf-Open/blob/main/docs/scorers.md.

## Push runs to a dashboard (optional)

Self-host TokenSurf Server (`docker compose up`) and add `--server`/`--key` to `tokensurf eval run`.
See https://github.com/Cem-Bas/TokenSurf-Open/blob/main/docs/self-hosting.md.
"""

_FILES: dict[str, str] = {
    "evals/example_deterministic.py": _EVAL_DETERMINISTIC,
    "evals/example_llm_judge.py": _EVAL_LLM_JUDGE,
    "evals/test_agent_quality.py": _TEST_AGENT_QUALITY,
    "README.md": _README,
}


def write_project(target: Path, *, force: bool = False) -> list[Path]:
    """Write the starter project under `target`. Returns the list of files written.

    Raises FileExistsError if `target` already exists and is non-empty, unless
    `force` is True (existing files are overwritten; unrelated files are left alone).
    """
    if target.exists() and any(target.iterdir()) and not force:
        raise FileExistsError(
            f"{target} already exists and is not empty (use --force to overwrite)"
        )
    written: list[Path] = []
    for rel_path, content in _FILES.items():
        full_path = target / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        written.append(full_path)
    return written
